// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReviewApp.Data;

namespace ReviewApp.Migrations
{
    [DbContext(typeof(ReviewContext))]
    [Migration("20200704034610_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("review_application")
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ReviewApp.Data.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("uq_company_name");

                    b.ToTable("company");
                });

            modelBuilder.Entity("ReviewApp.Data.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyId")
                        .HasColumnName("company_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("ImageUrl")
                        .HasColumnName("image_url")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("uq_product_name");

                    b.ToTable("product");
                });

            modelBuilder.Entity("ReviewApp.Data.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnName("content")
                        .HasColumnType("text");

                    b.Property<long>("ProductId")
                        .HasColumnName("product_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("review_date")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Stars")
                        .HasColumnName("stars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnName("title")
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReviewDate")
                        .HasName("idx_review_date");

                    b.HasIndex("Stars")
                        .HasName("idx_review_starts");

                    b.HasIndex("Title")
                        .HasName("idx_review_title");

                    b.ToTable("review");
                });

            modelBuilder.Entity("ReviewApp.Data.TextAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Json")
                        .HasColumnName("json")
                        .HasColumnType("text");

                    b.Property<double>("NegativeScore")
                        .HasColumnName("negative_score")
                        .HasColumnType("double");

                    b.Property<double>("NeutralScore")
                        .HasColumnName("neutral_score")
                        .HasColumnType("double");

                    b.Property<double>("PositiveScore")
                        .HasColumnName("positive_score")
                        .HasColumnType("double");

                    b.Property<DateTime>("QueryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("query_date")
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ReviewId")
                        .HasColumnName("review_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Sentiment")
                        .HasColumnName("sentiment")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("QueryDate")
                        .HasName("idx_text_analysis_query_date");

                    b.HasIndex("ReviewId");

                    b.HasIndex("Sentiment")
                        .HasName("idx_text_analysis_sentiment");

                    b.ToTable("text_analysis");
                });

            modelBuilder.Entity("ReviewApp.Data.Product", b =>
                {
                    b.HasOne("ReviewApp.Data.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewApp.Data.Review", b =>
                {
                    b.HasOne("ReviewApp.Data.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReviewApp.Data.TextAnalysis", b =>
                {
                    b.HasOne("ReviewApp.Data.Review", "Review")
                        .WithMany("TextAnalyses")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
